name: Infra plan

on:
  pull_request:
    branches:
      - main
    paths:
      - terraform/**
      - .github/workflows/plan.yaml
  workflow_dispatch:
    

env:
  tf_actions_working_dir: terraform

permissions:
  id-token: write
  contents: read

jobs:
  plan:
    name: Terraform plan stable
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.tf_actions_working_dir }}

    steps:
      - uses: actions/checkout@v4

      - name: Log in to Azure using OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_OIDC_PLAN_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_OIDC_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_OIDC_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: init
        run: terraform init
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_OIDC_PLAN_CLIENT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_OIDC_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_OIDC_TENANT_ID }}
          ARM_USE_OIDC: true

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Init TFLint
        run: tflint --init

      - name: Run TFLint
        id: lint
        run: tflint -f compact

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color --out=out.tfplan
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_OIDC_PLAN_CLIENT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_OIDC_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_OIDC_TENANT_ID }}
          ARM_USE_OIDC: true

      - name: Create the plan summary
        uses: actions/github-script@v7
        if: always()
        id: summary
        env:
          PLAN: "${{ steps.plan.outputs.stdout }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // 1. Prep the output
            const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
            #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
            <details><summary>Validation Output</summary>

            \`\`\`\n
            ${{ steps.validate.outputs.stdout }}
            \`\`\`

            </details>

            #### Terraform Lint 🤖\`${{ steps.lint.outcome }}\`

            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`

            <details><summary>Show Plan</summary>

            \`\`\`\n
            ${process.env.PLAN} 
            \`\`\`

            </details>

            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Working Directory: \`${{ env.tf_actions_working_dir }}\`, Workflow: \`${{ github.workflow }}\`*`;

            // 2. Set the output variable
            const fs = require('fs');
            fs.writeFileSync('${{ env.tf_actions_working_dir }}/summary.md', output);
            core.setOutput('summary', output);

      - name: Write the step summary
        if: always()
        run: cat summary.md >> $GITHUB_STEP_SUMMARY